# Generated by Django 4.2 on 2023-04-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
